on: push

name: Publish

jobs:
  publish:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest
        uses: actions/checkout@master
      - name: Install nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            override: true
      - name: Build docs
        uses: actions-rs/cargo@v1
        with:
          toolchain: nightly
          command: doc
          args: --no-deps
      - name: Move generated docs
        run: cp -r target/doc/ docs
      - name: Commit generated docs
        uses: stefanzweifel/git-auto-commit-action@v2.3.0
        with:
          commit_message: Apply automatic changes
          branch: ${{ github.head_ref }}
          file_pattern: docs/*
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}