on: push

name: Publish

jobs:
  publish:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest
        uses: actions/checkout@master
      - name: Install nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            override: true
      - name: Build docs
        uses: actions-rs/cargo@v1
        with:
          toolchain: nightly
          command: doc
          args: --no-deps
      - name: Move generated docs
        run: cp -r target/doc/* docs
      - name: Commit generated docs
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: |
          git config user.email "bob@technocreatives.com"
          git config user.name "Byggare Bob"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          git checkout master
          git add .
          # Only commit and push if we have changes
          git diff --quiet && git diff --staged --quiet || (git commit -m "Generated the docs again"; git push origin master)
